function formatNumber(value) {
  const numericValue = Number(value);

  if (!Number.isFinite(numericValue)) {
    return "—";
  }

  return numericValue.toFixed(2);
}

function formatChange(value) {
  const numericValue = Number(value);

  if (!Number.isFinite(numericValue)) {
    return "—";
  }

  const absoluteValue = Math.abs(numericValue).toFixed(2);

  if (numericValue < 0) {
    return `↓ ${absoluteValue}%`;
  }

  if (numericValue > 0) {
    return `↑ ${absoluteValue}%`;
  }

  return "0.00%";
}

function isImprovement(metric, change) {
  const numericChange = Number(change);

  if (!Number.isFinite(numericChange)) {
    return false;
  }

  switch (metric) {
    case "CO₂ Emissions":
    case "Waiting Time":
      return numericChange < 0;

    case "Average Speed":
      return numericChange > 0;

    default:
      return false;
  }
}

function ResultsComparisonTable({ comparison }) {
  if (!comparison) {
    return null;
  }

  const rows = [
    {
      metric: "CO₂ Emissions",
      baseline: comparison.baseline.total_co2,
      rl: comparison.rl.total_co2,
      change: comparison.percentage_change.co2,
    },
    {
      metric: "Waiting Time",
      baseline: comparison.baseline.total_waiting_time,
      rl: comparison.rl.total_waiting_time,
      change: comparison.percentage_change.waiting_time,
    },
    {
      metric: "Average Speed",
      baseline: comparison.baseline.average_speed,
      rl: comparison.rl.average_speed,
      change: comparison.percentage_change.average_speed,
    },
  ];

  return (
    <section className="ecotwin-comparison-card">
      <div className="ecotwin-section-heading">
        <span className="ecotwin-eyebrow">
          Simulation Results
        </span>

        <h2>Baseline vs RL Controller</h2>

        <p>
          Comparison of EcoTwin simulation outputs using conventional traffic
          control and reinforcement learning.
        </p>
      </div>

      <div className="ecotwin-table-wrapper">
        <table className="ecotwin-results-table">
          <thead>
            <tr>
              <th>Metric</th>
              <th>Baseline</th>
              <th>RL Controller</th>
              <th>Change</th>
            </tr>
          </thead>

          <tbody>
            {rows.map((row) => {
              const improvement = isImprovement(
                row.metric,
                row.change
              );

              return (
                <tr key={row.metric}>
                  <td>
                    <strong>{row.metric}</strong>
                  </td>

                  <td>{formatNumber(row.baseline)}</td>

                  <td>{formatNumber(row.rl)}</td>

                  <td>
                    <span
                      className={`ecotwin-change-pill ${
                        improvement
                          ? "ecotwin-change-positive"
                          : "ecotwin-change-negative"
                      }`}
                    >
                      {formatChange(row.change)}
                    </span>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      <p className="ecotwin-simulation-note">
        Values shown are generated by the EcoTwin SUMO simulation and are not
        real-world measurements.
      </p>
    </section>
  );
}

export default ResultsComparisonTable;